---
- name: Creates directory
  become: true
  file:
    path: ~/web
    state: directory

- name: Copy dist/main page
  become: true
  shell: |
    ls ~/project/backend
  template:
    src: "~/project/backend/dist/main.js"
    dest: "~/web/main.js"

- name: Executing node
  become: true
  shell: |
    pm2 start ~/web/main.js -f