---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy dist/main page
  template:
    src: "./dist/main.js"
    dest: "~/web/main.js"

- name: Executing node
  shell: |
    pm2 start ~/web/main.js -f